spring:
  application:
    name: execution
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      # 1. 服务发现配置
      discovery:
        server-addr: 127.0.0.1:8848
      # 2. 配置中心配置
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  # Kafka配置
  kafka:
    bootstrap-servers: 172.24.176.31:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 异步发送配置
      acks: 1
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      # 异步发送
      enable-idempotence: false

server:
  port: 7083

# 日志配置
logging:
  level:
    root: INFO
    com.example.execution: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'